language: python
#dist: trusty

env:
  - TOXENV=py27
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=py36

install:
  - pip install -U tox

script:
  - tox

after_success:
  - bash <(curl -s https://codecov.io/bash)
